<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{{env('BASE_URL','http://127.0.0.1:8000')}}</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>{{env('BASE_URL')}}/register</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>{{env('BASE_URL')}}/sign-in</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>{{env('BASE_URL')}}/about-us</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>{{env('BASE_URL')}}/faq</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>{{env('BASE_URL')}}/blog</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  @for($i = 1;$i <= $blogPages ; $i++)
  <url>
    <loc>{{env('BASE_URL')}}/blog?page={{$i}}</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  @endfor
  @if(!empty($categories))
    @foreach($categories as $cat)
      <url>
        <loc>{{env('BASE_URL')}}/category/{{$cat->slug}}</loc>
        <lastmod>{{$cat->updated_at->format('Y-m-d\TH:i:s')}}+00:00</lastmod>
        <priority>0.7</priority>
      </url>
    @endforeach
  @endif
  @if(!empty($blogs))
    @foreach($blogs as $blog)
      <url>
        <loc>{{env('BASE_URL')}}/blog/{{$blog->slug}}</loc>
        <lastmod>{{$blog->updated_at->format('Y-m-d\TH:i:s')}}+00:00</lastmod>
        <priority>{{$blog->featured == 0 ? 0.7 : 0.8}}</priority>
      </url>
    @endforeach
  @endif
  <url>
    <loc>{{env('BASE_URL')}}/terms-of-use</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>{{env('BASE_URL')}}/terms-of-service</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>{{env('BASE_URL')}}/privacy-policy</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>{{env('BASE_URL')}}/contact-us</loc>
    <lastmod>2018-05-12T04:46:53+00:00</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>
